
--
-- Дамп данных таблицы `grammartest`
--

INSERT INTO `grammartest` (`id`, `grammarPost`, `question`, `answer`, `pos`, `image`) VALUES
(4, 1, 'Это моя кошка.', 'It is my cat.', 1, '4.svg'),
(7, 1, 'Он ваш учитель.', 'He is your teacher.', 5, '7.svg'),
(8, 1, 'Дай им их книги.', 'Give them their books.', 6, '8.svg'),
(11, 2, 'Это моя собака.', 'It is my dog.', 1, '11.svg'),
(12, 2, 'Это мои книги.', 'They are my books.', 2, '12.svg'),
(13, 2, 'Это его очки.', 'They are his glasses.', 4, '13.svg'),
(14, 2, 'Это твоя гитара.', 'It is your guitar.', 6, '14.svg'),
(15, 2, 'Это наши дома.', 'They are our houses.', 3, '15.svg'),
(16, 2, 'Это их дети.', 'They are their children.', 5, '16.svg'),
(17, 3, '{In/On/At} a cafe.', 'In', 1, '17.svg'),
(18, 3, '{In/On/At} the train.', 'On', 2, '18.svg'),
(19, 3, '{In/On/At} 12 o’clock.', 'At', 4, '19.svg'),
(20, 3, '{In/On/At} London.', 'In', 3, '20.svg'),
(21, 3, '{In/On/At} night.', 'At', 5, '21.svg'),
(22, 3, '{In/On/At} the plane.', 'On', 6, '22.svg'),
(23, 1, 'Она любит своих собак.', 'She loves her dogs.', 2, '23.svg'),
(24, 1, 'Это их дом.', 'It is their house.', 3, '24.svg'),
(25, 1, 'Мне нравится наш сад.', 'I like our garden.', 4, '25.svg'),
(27, 4, 'They {am/is/are} not teachers.', 'are', 2, '27.svg'),
(28, 4, '{Am/Is/Are} he a new manager?', 'Is', 5, '28.svg'),
(30, 4, '{Am/Is/Are} they good friends?', 'Are', 6, '30.svg'),
(31, 4, 'She {am/is/are} not from Moscow.', 'is', 3, '31.svg'),
(32, 5, 'There {is/are} a book on the table.', 'is', 1, '32.svg'),
(33, 5, 'There  {is/are}  a book, a phone and a pen on the table.', 'is', 2, '33.svg'),
(34, 5, 'There {is/are} my friends in the room.', 'are', 3, '34.svg'),
(36, 5, 'There {is/are} not any milk at home — let’s go to the shop.', 'is', 5, '36.svg'),
(37, 5, 'There {is/are} some people in the street.', 'are', 4, '37.svg'),
(38, 5, '{Is/Are} there many rooms in your house?', 'Are', 6, '38.svg'),
(39, 6, 'Она не умеет водить машину.', 'She can’t drive.', 3, '39.svg'),
(40, 6, 'Я умею бегать и прыгать.', 'I can run and jump.', 1, '40.svg'),
(41, 6, 'Он умеет плавать.', 'He can swim.', 2, '41.svg'),
(42, 6, 'Ты не умеешь читать быстро.', 'You can’t read fast.', 5, '42.svg'),
(43, 6, 'Вы умеете хорошо готовить.', 'You can cook well.', 6, '43.svg'),
(44, 6, 'Мы не умеем говорить  по-испански.', 'We can’t speak Spanish.', 4, '44.svg'),
(45, 7, 'Я работаю в банке.', 'I work in a bank.', 1, '45.svg'),
(46, 7, 'Он любит чай.', 'He likes tea.', 2, '46.svg'),
(47, 7, 'Она не ест мясо.', 'She doesn’t eat meat.', 3, '47.svg'),
(48, 7, 'Мы просыпаемся в 8  каждое утро.', 'We wake up at 8 o’clock every morning.', 4, '48.svg'),
(49, 7, 'Что ты ешь на завтрак?', 'What do you eat for breakfast?', 6, '49.svg'),
(50, 7, 'Они любят мороженое?', 'Do they like ice cream?', 5, '50.svg'),
(51, 8, 'Я был дома вчера.', 'I was at home yesterday.', 1, '51.svg'),
(52, 8, 'Вы были там?', 'Were you there?', 3, '52.svg'),
(53, 8, 'Они были правы?', 'Were they right?', 4, '53.svg'),
(54, 8, 'Они не были друзьями.', 'They were not friends.', 2, '54.svg'),
(55, 8, 'Она была хорошим человеком.', 'She was a good person.', 5, '55.svg'),
(56, 8, 'Где ты был?', 'Where were you?', 6, '56.svg'),
(57, 9, 'He {enjoyed/enjoy/was enjoy} his holiday.', 'enjoyed', 1, '57.svg'),
(58, 9, 'Did you {working/work/worked} yesterday?', 'work', 4, '58.svg'),
(60, 9, 'I {did see/see/saw} you yesterday.', 'saw', 5, '60.svg'),
(61, 9, 'We {did like/liked/like} this film.', 'liked', 2, '61.svg'),
(62, 9, 'Did she {came/coming/come} by bus?', 'come', 3, '62.svg'),
(63, 10, 'Я ем сейчас.', 'I am eating now.', 1, '63.svg'),
(64, 10, 'Они не работают сейчас.', 'They aren’t working now.', 2, '64.svg'),
(66, 10, 'Ты сидишь на моем стуле.', 'You are sitting on my chair.', 4, '66.svg'),
(68, 10, 'Что сейчас делают дети?', 'What are the children doing now?', 6, '68.svg'),
(69, 10, 'Зачем он делает это?', 'Why is he doing it?', 5, '69.svg'),
(70, 9, 'He {not eat/didn’t eat/are not} this soup.', 'didn’t eat', 6, '70.svg'),
(71, 4, 'I {am/is/are} a good friend.', 'am', 1, '71.svg'),
(72, 4, '{Am/Is/Are} you Russian?', 'Are', 4, '72.svg'),
(73, 10, 'Она сейчас говорит  по-английски?', 'Is she speaking English now?', 3, '73.svg'),
(74, 12, 'Я только что закончил эту работу.', 'I have just finished this work.', 1, '74.svg'),
(75, 12, 'Она ещё не пришла.', 'She hasn’t come yet.', 2, '75.svg'),
(76, 12, 'Они видели этот фильм?', 'Have they seen this film?', 3, '76.svg'),
(77, 12, 'Ты уже ответил на вопрос?', 'Have you answered the question yet?', 4, '77.svg'),
(78, 12, 'Ты был в Париже?', 'Have you ever been to Paris?', 5, '78.svg'),
(79, 12, 'Я никогда не видел этого человека.', 'I have never seen this person.', 6, '79.svg'),
(80, 13, '{This/That/These/Those} books are Tony’s.', 'These', 1, '80.svg'),
(81, 13, '{This/That/These/Those} is my friend, Paolo.', 'This', 3, '81.svg'),
(82, 13, '{This/That/These/Those} boy over there is Steve.', 'That', 2, '82.svg'),
(83, 13, 'Did you like {this/that/these/those} films?', 'these', 4, '83.svg'),
(84, 13, '{This/That/These/Those} is her boyfriend.', 'This', 5, '84.svg'),
(85, 13, 'Who are {this/that/these/those} people over there?', 'those', 6, '85.svg'),
(86, 14, 'I have {some/any} milk at home.', 'some', 1, '86.svg'),
(87, 14, 'Do you have {some/any} questions?', 'any', 2, '87.svg'),
(88, 14, 'I can’t see {some/any} mistakes here.', 'any', 4, '88.svg'),
(89, 14, 'He doesn’t have {some/any} money.', 'any', 3, '89.svg'),
(90, 14, 'She can give us  {some/any} money.', 'some', 5, '90.svg'),
(91, 14, 'Are there  {some/any}  shops near here?', 'any', 6, '91.svg'),
(92, 15, 'There aren’t {much/many/a lot of} cars in the street.', 'many', 2, '92.svg'),
(93, 15, 'Do you have {much/many/a lot of} time?', 'much', 1, '93.svg'),
(94, 15, 'Do you have {much/many/a lot of} new projects?', 'many', 4, '94.svg'),
(95, 15, 'I have got {much/many/a lot of} free time.', 'a lot of', 3, '95.svg'),
(96, 15, 'She knows {much/many/a lot of} of English words.', 'a lot of', 5, '96.svg'),
(97, 15, 'Don’t drink too {much/many/a lot of} coffee.', 'much', 6, '97.svg'),
(98, 16, 'Он самый счастливый человек.', 'He is the happiest person.', 2, '98.svg'),
(99, 16, 'Она старше, чем ее брат.', 'She is elder than her brother.', 1, '99.svg'),
(100, 16, 'Вчера я смотрел самый плохой фильм в жизни.', 'Yesterday I watched the worst film in my life.', 4, '100.svg'),
(101, 16, 'Русский сложнее, чем английский.', 'Russian is more difficult than English.', 5, '101.svg'),
(102, 16, 'Эта книга дороже, чем та.', 'This book is more expensive than that one.', 3, '102.svg'),
(103, 16, 'Летом теплее, чем весной.', 'Summer is warmer than spring.', 6, '103.svg'),
(104, 17, 'Он ненавидит путешествовать самолетом.', 'He hates travelling by plane.', 1, '104.svg'),
(105, 17, 'Она любит плавать в море.', 'She loves swimming in the sea.', 2, '105.svg'),
(106, 17, 'Нам нравится учить английский каждый день.', 'We like learning English every day.', 3, '106.svg'),
(107, 17, 'Они не выносят мыть посуду.', 'They can\'t stand washing the dishes.', 6, '107.svg'),
(108, 17, 'Он не хочет ждать.', 'He doesn\'t feel like waiting.', 4, '108.svg'),
(109, 17, 'Мне нравится говорить на английском.', 'I enjoy speaking English.', 5, '109.svg'),
(110, 18, 'Мне не приходится этого делать.', 'I don’t have to do this.', 3, '110.svg'),
(111, 18, 'Ему приходится помогать своему другу.', 'He has to help his friend.', 2, '111.svg'),
(112, 18, 'Она вынуждена много работать?', 'Does she have to work much?', 4, '112.svg'),
(113, 18, 'Я вынужден идти.', 'I have to go.', 1, '113.svg'),
(114, 18, 'Я не обязан носить галстук на работе.', 'I don’t have to wear a tie at work.', 6, '114.svg'),
(115, 18, 'Им приходится учить китайский язык.', 'They have to learn Chinese.', 5, '115.svg'),
(116, 19, 'I {am going/is going} to visit my granny.', 'am going', 1, '116.svg'),
(117, 19, 'He {am going/is going} to do his homework.', 'is going', 2, '117.svg'),
(118, 19, 'It  {am going/is going} to rain.', 'is going', 4, '118.svg'),
(119, 19, 'They {are going/is going} to leave school.', 'are going', 3, '119.svg'),
(120, 19, 'We {are going/is going} to watch a new film.', 'are going', 5, '120.svg'),
(121, 19, 'I {am going/is going} to do it tonight.', 'am going', 6, '121.svg'),
(122, 22, 'Я сделаю домашнее задание завтра.', 'I will do my homework tomorrow.', 1, '122.svg'),
(123, 22, 'Она уйдет на работу рано утром.', 'She will go to work early in the morning.', 6, '123.svg'),
(124, 22, 'Он вернется домой скоро.', 'He will come home soon.', 5, '124.svg'),
(125, 22, 'Мы отправимся в отпуск послезавтра.', 'We will go on holiday the day after tomorrow.', 2, '125.svg'),
(126, 22, 'Вы не забудете об этом никогда.', 'You will never forget about it.', 4, '126.svg'),
(127, 22, 'Ты пойдешь в школу в следующем году.', 'You will go to school next year.', 3, '127.svg'),
(128, 21, 'Сегодня теплее, чем вчера.', 'Today it is warmer than it was yesterday.', 6, '128.svg'),
(129, 21, 'Вторая книга не такая увлекательная, как первая.', 'The second book is not as fascinating as the first one.', 2, '129.svg'),
(130, 21, 'Он еще слишком молод.', 'He is still too young.', 3, '130.svg'),
(131, 21, 'Этот фильм такой же смешной, как и тот.', 'This film is as funny as that.', 1, '131.svg'),
(132, 21, 'У нас не достаточно времени на этот проект.', 'We don’t have enough time for this project.', 5, '132.svg'),
(133, 21, 'Он не достаточно терпелив.', 'He is not patient enough.', 4, '133.svg'),
(134, 20, 'I don’t have {much/many/little} time.', 'much', 1, '134.svg'),
(135, 20, 'They don’t have {many/few/much} money.', 'much', 2, '135.svg'),
(136, 20, 'We have {much/few/a little} time to do this work, it is enough', 'a little', 4, '136.svg'),
(137, 20, 'We have {little/a little/much} time to do this work, it is not enough', 'little', 3, '137.svg'),
(138, 20, 'We have {few/a few/many} textbooks, it is not enough for the class.', 'few', 5, '138.svg'),
(139, 20, 'We have {a few/a little/many} textbooks, it is enough for the class.', 'a few', 6, '139.svg'),
(140, 23, 'We {can/could/will be able to} to go to the country next weekend.', 'will be able to', 5, '140.svg'),
(141, 23, 'I {can/am able speak/am able to speak} speak French fluently.', 'can', 1, '141.svg'),
(142, 23, 'He {can/could/is able to} help us but he didn’t want to.', 'could', 6, '142.svg'),
(143, 23, 'She {is able to/able to/was able to} dance ballet when she was younger.', 'was able to', 3, '143.svg'),
(144, 23, 'You {will be able to/will able to/could} speak English much better if you learn harder.', 'will be able to', 4, '144.svg'),
(145, 23, 'He {can/could/is able to} drive a car when he was 18.', 'could', 2, '145.svg'),
(146, 24, 'You {may/might/allowed} leave now.', 'may', 1, '146.svg'),
(147, 24, 'He {is allowed to/will be allowed to/might} do it yesterday but he didn’t do it.', 'might', 2, '147.svg'),
(148, 24, 'You {might/may/are allowed to be} be right but I am not sure.', 'may', 6, '148.svg'),
(149, 24, 'I {may/might/will be allowed to} drive a car next year.', 'will be allowed to', 3, '149.svg'),
(150, 24, 'They {may/might/are allowed to be} be in trouble  – let’s help them', 'might', 5, '150.svg'),
(151, 24, 'He {was allowed to/were allowed to/was allowed go} go there by his mother.', 'was allowed to', 4, '151.svg'),
(152, 25, 'Потрясающая облегающая шёлковая блузка черного цвета делового стиля.', 'A lovely tight black business style blouse.', 4, '152.svg'),
(153, 25, 'Восхитительная новая облегающая кожаная юбка черного цвета.', 'An amazing tight new black leather skirt.', 2, '153.svg'),
(154, 25, 'Чудесный огромный новый кирпичный дом.', 'A wonderful huge new brick house.', 1, '154.svg'),
(155, 25, 'Элегантное старое платье свободного покроя жёлтого цвета из китайского шёлка.', 'An elegant loose old yellow Chinese silk dress.', 3, '155.svg'),
(156, 25, 'Ужасные старые грязные растянутые джинсы из Китая.', 'Ugly stretched old dirty Chinese jeans.', 5, '156.svg'),
(157, 25, 'Новый модный пиджак, облегающий фигуру, из США.', 'A trendy tight new American jacket.', 6, '157.svg'),
(158, 26, 'Они, возможно, не успеют доделать эту работу на этой неделе.', 'They may/might not have enough time to finish this job this week.', 3, '158.svg'),
(159, 26, 'Вероятно, она не сможет прийти на работу завтра.', 'She probably won’t be able to go to work tomorrow.', 2, '159.svg'),
(160, 26, 'Я встречусь с Вами в пятницу.', 'I will meet you on Friday.', 6, '160.svg'),
(161, 26, 'Возможно, он приедет послезавтра.', 'He may arrive the day after tomorrow.', 5, '161.svg'),
(162, 26, 'Они не поедут в отпуск за рубеж следующим летом.', 'They won’t go on holiday abroad next summer.', 1, '162.svg'),
(163, 26, 'Он мог бы реализовать этот проект в этом месяце.', 'He might/could realize this project this month.', 4, '163.svg'),
(164, 27, 'Когда-то давно они жили в Париже.', 'They used to live in Paris.', 1, '164.svg'),
(165, 27, 'В прошлом они были вместе.', 'They used to be together in the past.', 2, '165.svg'),
(166, 27, 'Она ходила в школу искусств в детстве?', 'Did she use to go to the arts school in her childhood?', 6, '166.svg'),
(167, 27, 'Он много путешествовал по миру в прошлом.', 'He used to travel a lot around the world in the past.', 4, '167.svg'),
(168, 27, 'Они не ходили в школьную библиотеку в детстве.', 'They didn’t use to go to the school library in their childhood.', 5, '168.svg'),
(169, 27, 'Я жила в Лондоне в прошлом.', 'I used to live in London in the past.', 3, '169.svg'),
(170, 28, 'Я уже позавтракал.', 'I have already had my breakfast.', 1, '170.svg'),
(171, 28, 'Они сходили в театр вчера.', 'They went to the theatre yesterday.', 2, '171.svg'),
(172, 28, 'Она еще не пришла на работу.', 'She has not come to work yet.', 5, '172.svg'),
(173, 28, 'Они поженились в 2000 году.', 'They got married in 2000.', 6, '173.svg'),
(174, 28, 'Они уехали на прошлой неделе.', 'They left last week.', 4, '174.svg'),
(175, 28, 'Он только что зашёл домой.', 'He has just come home.', 3, '175.svg'),
(176, 29, 'Если добавить сыр, он растает.', 'If you add some cheese, it melts.', 5, '176.svg'),
(177, 29, 'Если оставить шоколад в тепле, он растает.', 'If you leave some chocolate in a warm place, it melts.', 4, '177.svg'),
(178, 29, 'Если нажать на эту кнопку, откроется та дверь.', 'If you press this button, that door opens.', 1, '178.svg'),
(179, 29, 'Если я хлопаю в ладоши, то моя собака садится.', 'If I clap my hands, my dog sits down.', 3, '179.svg'),
(180, 29, 'Если твои волосы намокнут на улице, ты замёрзнешь.', 'If your hair gets wet in the street, you get cold.', 2, '180.svg'),
(181, 29, 'Если температура будет 0 градусов, то всё замёрзнет на улице.', 'If the temperature is 0 degrees, everything freezes outside.', 6, '181.svg'),
(182, 30, 'Если Вы достанете билеты, мы сможем пойти на этот концерт.', 'If you get tickets, we will be able to go to this concert.', 6, '182.svg'),
(183, 30, 'Если эффект глобального потепления усилится, то климат на нашей планете изменится.', 'If the global warming effect gets worse, the climate of our planet will change.', 2, '183.svg'),
(184, 30, 'Если мы поедем на автобусе, то мы опоздаем.', 'If we take a bus, we will be late.', 5, '184.svg'),
(185, 30, 'Если ты поторопишься, то мы приедем вовремя.', 'If you hurry up, we will come in time.', 4, '185.svg'),
(186, 30, 'Если завтра будет хорошая погода, мы пойдем гулять в парк.', 'If the weather is fine tomorrow, we will go for a walk to the park.', 1, '186.svg'),
(187, 30, 'Если мы накопим достаточно средств, мы поедем в отпуск за границу.', 'If we save enough money, we will go on holiday abroad.', 3, '187.svg'),
(188, 31, 'Если бы я был на Вашем месте, я бы так никогда не сделал.', 'If I were in your place, I would never do like this.', 5, '188.svg'),
(189, 31, 'В Вашей ситуации я бы заказал такси.', 'If I were in your shoes, I would take a taxi.', 6, '189.svg'),
(190, 31, 'Если бы он был старше, он бы понял меня.', 'If he were older, he would understand me.', 3, '190.svg'),
(191, 31, 'Если бы у меня было много денег, я бы купил себе остров.', 'If I had a lot of money, I would buy an island.', 1, '191.svg'),
(192, 31, 'Если бы она была младше, она бы не поняла нас.', 'If she were younger, she would not understand us.', 4, '192.svg'),
(193, 31, 'На Вашем месте я бы пожертвовал деньги на благотворительность.', 'If I were you, I would give some money to charity.', 2, '193.svg'),
(194, 32, 'Я учусь в университете 4 года.', 'I have been studying at the university for 4 years.', 2, '194.svg'),
(195, 32, 'Я закончил университет в этом году.', 'I have graduated from the university this year.', 1, '195.svg'),
(196, 32, 'Они успешно реализовали данный проект.', 'They have realized successfully this project.', 3, '196.svg'),
(197, 32, 'Они работают в Китае уже 5 лет.', 'They have been working in China for 5 years.', 6, '197.svg'),
(198, 32, 'Они работают над этим проектом уже пару лет.', 'They have already been working upon this project for a couple of years.', 4, '198.svg'),
(199, 32, 'Мы вернулись из рабочей поездки недавно.', 'We have come back from a business trip recently.', 5, '199.svg'),
(200, 33, 'Мы пойдем в ресторан на этих выходных.', 'We will go to the restaurant this weekend.', 4, '200.svg'),
(201, 33, 'Мой поезд отходит завтра вечером.', 'My train leaves tomorrow evening.', 5, '201.svg'),
(202, 33, 'Мы идём в театр сегодня вечером.', 'We are going to the theatre tonight.', 3, '202.svg'),
(203, 33, 'Наш самолет прибывает рано утром.', 'Our plane arrives early in the morning.', 6, '203.svg'),
(204, 33, 'Я собираюсь отправиться в путешествие в Индию.', 'I am going to go travelling to India.', 2, '204.svg'),
(205, 33, 'Мы выходим на улицу.', 'We are about to go outside.', 1, '205.svg'),
(206, 34, 'Он сказал мне, что он встаёт в 7 часов каждое утро.', 'He said to me that he got up at 7 o’clock every morning.', 1, '206.svg'),
(207, 34, 'Вы сказали мне, что Вы работаете много на данный момент.', 'You said to me that you were working a lot then.', 4, '207.svg'),
(208, 34, 'Они сказали мне, что они закончат эту работу завтра, к полудню.', 'They said to me that they would have finished that work by midday the following day.', 6, '208.svg'),
(209, 34, 'Он сказал мне, что он учился в университете 5 лет.', 'He said to me that he was studying/had been studying at the university for 5 years.', 5, '209.svg'),
(210, 34, 'Они сказали мне, что они сходили в кинотеатр вчера.', 'They said to me that they had gone to the cinema the day before.', 2, '210.svg'),
(211, 34, 'Они сказали мне, что они пойдут за покупками на выходных.', 'They said to me that they would go shopping at the weekend.', 3, '211.svg'),
(212, 35, 'Он сказал мне, что приехал в <i>этот</i> город <i>недавно</i>.', 'He said to me that he had come to <i>that</i> city <i>recently</i>.', 5, '212.svg'),
(213, 35, 'Она рассказала мне, что идёт в библиотеку <i>вечером</i>', 'She told me that she was going to the library <i>that night</i>.', 1, '213.svg'),
(214, 35, 'Он сказал мне, что она очень занята <i>сейчас</i>.', 'He said to me that she was very busy <i>then</i>.', 4, '214.svg'),
(215, 35, 'Они сказали мне, что они живут <i>здесь</i>.', 'They said to me that they lived <i>there</i>.', 6, '215.svg'),
(216, 35, 'Он рассказал мне, что сдал сложный экзамен <i>вчера</i>.', 'He told me that he had passed a difficult exam <i>the day before</i>.', 2, '216.svg'),
(217, 35, 'Они рассказали мне, что уезжают за город <i>завтра</i>.', 'They told me that they would go to the country <i>the next day</i>.', 3, '217.svg'),
(218, 36, 'Моё новое платье будет готово завтра.', 'I will have my new dress made tomorrow.', 5, '218.svg'),
(219, 36, 'Я делаю маникюр каждую неделю.', 'I have my manicure done every week.', 1, '219.svg'),
(220, 36, 'Я делаю педикюр каждый месяц.', 'I have my pedicure done every month.', 2, '220.svg'),
(221, 36, 'Я делаю стрижку каждый месяц.', 'I have my hair cut every month.', 3, '221.svg'),
(222, 36, 'Мою машину отремонтировали вчера.', 'I had my car repaired yesterday.', 4, '222.svg'),
(223, 36, 'Его кошелёк украли в магазине только что!', 'He has just had his wallet stolen at the shop!', 6, '223.svg'),
(224, 37, 'Он, должно быть, забыл про подарок.', 'He must have forgotten about a present.', 1, '224.svg'),
(226, 37, 'Ты, возможно, оставил свой телефон в машине.', 'You could have left your phone in the car.', 6, '226.svg'),
(227, 37, 'Им следовало бы обсудить это.', 'They should have discussed it.', 4, '227.svg'),
(228, 37, 'Вероятно, они уже вернулись домой.', 'They might have already come home.', 3, '228.svg'),
(229, 37, 'Должно быть, он ушёл ночью.', 'He must have gone at night.', 5, '229.svg'),
(230, 37, 'Возможно, она была права.', 'She could have been right.', 2, '230.svg'),
(231, 38, 'Мне бы хотелось купить им подарки на Рождество.', 'I wish I would buy them Christmas presents.', 4, '231.svg'),
(232, 38, 'Если бы только она не опоздала.', 'If only she had not been late.', 2, '232.svg'),
(233, 38, 'Мне хотелось бы поехать в отпуск в тёплые края.', 'I wish I would go on holiday to some warm country.', 1, '233.svg'),
(234, 38, 'Я бы предпочёл, чтобы ты прочитал эту книгу.', 'I’d rather you had read that book.', 3, '234.svg'),
(235, 38, 'Если бы только он послушал эту интересную историю.', 'If only he would listen to that interesting story.', 5, '235.svg'),
(236, 38, 'Мне хотелось бы, что вы были здоровы.', 'I wish you were healthy.', 6, '236.svg'),
(237, 39, 'Он поёт так громко.', 'He is singing so loudly.', 4, '237.svg'),
(238, 39, 'Она танцует так красиво.', 'She is dancing so beautifully.', 3, '238.svg'),
(239, 39, 'Это такой приятный подарок для меня.', 'It is such a nice present for me.', 1, '239.svg'),
(240, 39, 'Вы так добры и любезны.', 'You are so kind and polite.', 2, '240.svg'),
(241, 39, 'Они разговаривают так тихо.', 'They are speaking so quietly.', 5, '241.svg'),
(242, 39, 'У них такой уютный дом.', 'They have such a cozy house.', 6, '242.svg'),
(243, 40, 'У неё самый красивый голос в хоре.', 'She has got the most beautiful voice in the choir.', 1, '243.svg'),
(244, 40, 'Это самая популярная пиццерия в этом городе.', 'It is the most popular pizza place in this city.', 3, '244.svg'),
(245, 40, 'У них самая дорогая машина.', 'They have got the most expensive car.', 2, '245.svg'),
(246, 40, 'Это наименее населенный город в этой стране.', 'It is the least populated city in this country.', 5, '246.svg'),
(247, 40, 'Это был наименее сложный экзамен.', 'It has been the least difficult exam.', 4, '247.svg'),
(248, 40, 'Это самый населенный город в этом крае.', 'It is the most populated city in this region.', 6, '248.svg'),
(249, 41, 'He said to me that he {will do/would do/will be doing} it the following week.', 'would do', 1, '249.svg'),
(250, 41, 'I said to you that I {will have been doing/will have done/would have done} that task by the following morning.', 'would have done', 3, '250.svg'),
(251, 41, 'She told me that she {will be doing/would be doing/would have done} her homework that evening.', 'would be doing', 2, '251.svg'),
(252, 41, 'We promised them that we {will visit/will be visiting/would visit} them the next summer.', 'would visit', 4, '252.svg'),
(253, 41, 'They told us that they {will have come/will have came/would have come} home by 7 o’clock.', 'would have come', 5, '253.svg'),
(257, 41, 'He replied to me that he {will be ready/would be ready/would have been ready} by 9 o’clock.', 'would have been ready', 8, '257.svg'),
(259, 42, 'She {have/has/will have} to go there alone tomorrow.', 'will have', 3, '259.svg'),
(260, 42, 'I {will have/must/are} to go there by bus.', 'will have', 1, '260.svg'),
(261, 42, 'He {have/has/had} to do this job alone yesterday.', 'had', 2, '261.svg'),
(262, 42, 'We {are/must/have} to meet up at 6.', 'are', 4, '262.svg'),
(263, 42, 'He {had to be/must be/is} late for the meeting yesterday.', 'had to be', 6, '263.svg'),
(264, 42, 'We {must/have/are} help them.', 'must', 5, '264.svg');
