
--
-- Дамп данных таблицы `teachercertificate`
--

INSERT INTO `teachercertificate` (`id`, `teacher_id`, `image`, `main`, `pos`, `title`, `teacherCertificateType`) VALUES
(17, 119, '17.jpg', '0', 2, 'Cambridge English Level 2 Certificate in ESOL International (Advanced)', 2),
(18, 119, '18.jpg', '0', 3, 'Cambridge English Teaching Knowledge Test Module 2 \"Lesson planning and use of resources for language teaching\"', 2),
(19, 119, '19.jpg', '0', 4, 'Cambridge English Teaching Knowledge Test Module 3 \"Managing the teaching and learning process\"', 2),
(20, 125, '20.jpg', '0', 1, 'Diploma Bachelor of Secondary Education (Communication Arts: English)', 1),
(21, 125, '21.jpg', '0', 2, 'Professional Teacher (Secondary) Certificate', 2),
(22, 125, '22.jpg', '0', 4, 'Certificate of Training for program in Teaching English To Speakers of Other Languages (TESOL)', 2),
(23, 125, '23.jpg', '0', 7, 'Certificate of Completion for the Course on \"Seminar on Teaching English as a Second/Foreign Language\"', 2),
(24, 125, '24.jpg', '0', 8, 'Certificate of Participation at the International Education Conference \"How to be an Effective and Successful Educator\"', 2),
(25, 125, '25.jpg', '0', 9, 'Certificate of Attendance for having succesfully completed the Seminar for Teachers on Fundamentals of Teaching English Language Skills', 2),
(26, 119, '26.jpg', '0', 6, 'Удостоверение о повышении квалификации по программе \"Актуальные вопросы реализации требования ФГОС в инклюзивном образовании обучающихся с ограниченными возможностями здоровья\"', 4),
(31, 119, '31.jpg', '0', 7, 'Удостоверение о повышении квалификации по программе \"Реализация ФГОС в начальном образовании: методические аспекты современного учебного занятия\"', 4),
(34, 118, '34.jpg', '0', 3, 'Удостоверение о повышении квалификации по теме \"Инновационные процессы в преподавании иностранных языков в свете ФГОС\"', 4),
(35, 118, '35.jpg', '0', 5, 'Удостоверение о повышении квалификации по дополнительной профессиональной программе \"Использование нелинейных презентаций и \"интерактивных стен\" в учебном процессе в вузе\"', 4),
(41, 124, '41.jpg', '0', 10, 'Сертификат о повышении квалификации по теме \"Информационно-коммуникационные технологии в образовательном процессе\"', 2),
(42, 124, '42.jpg', '0', 9, 'Сертификат о прохождении обучения на мастер-классе \"Использование методики тренингов при проведении занятий в условиях КСО\"', 2),
(43, 124, '43.jpg', '0', 4, 'Cambridge English Teaching Knowledge Test in Module 2 \"Lesson planning and use of resources for language teaching\"', 2),
(45, 124, '45.jpg', '0', 13, 'Cambridge English Certificate of Attendance \"Особенности подготовки к Кембриджским экзаменам уровень A1-B1\"', 2),
(53, 118, '53.jpg', '0', 4, 'Сертификат о повышении квалификации по программе \"Организация исследовательской деятельности учащихся\"', 2),
(54, 124, '54.jpg', '0', 16, 'Cambridge English Certificate of Completion \"Preparing for an exam\"', 2),
(55, 124, '55.jpg', '0', 15, 'Cambridge English Certificate of Completion \"Running an exam\"', 2),
(56, 124, '56.jpg', '0', 14, 'Cambridge English Certificate of Completion \"Dealing with malpractice, incidents and inspections\"', 2),
(57, 118, '57.jpg', '0', 16, 'Свидетельство о публикации методического материала на тему \"Методика обучения английскому языку на начальном этапе в средней школе\"', 5),
(58, 118, '58.jpg', '0', 15, 'Сертификат участника семинара \"Teaching 21th Century Learners\"', 2),
(59, 118, '59.jpg', '0', 14, 'Свидетельство о публикации методического материала на тему \"Урок в 2 классе \"English\" И. Н. Верещагиной\"', 5),
(60, 120, '60.jpg', '0', 1, 'Teflen Training College Certificate in \"Teaching English to Speakers of Other Languages (TESOL)», «Teaching English as a Foreign Language (TEFL)»', 2),
(61, 119, '61.jpg', '0', 8, 'Cambridge English Certificate of Attendance \"Новые подходы в преподавании английского языка в современной школе\"', 2),
(62, 119, '62.jpg', '0', 9, 'Сертификат о прослушивании курса лекций на тему \"Bring your learning into FOCUS\"', 2),
(65, 122, '65.jpg', '0', 5, 'Удостоверение о повышении квалификации по программе \"Современные технологии в преподавании практического курса иностранного языка\"', 4),
(66, 122, '66.jpg', '0', 8, 'Удостоверение о повышении квалификации по теме \"Способы формирования и оценивания метапредметных результатов и УУД в предметах гуманитарного цикла\"', 4),
(67, 122, '67.jpg', '0', 7, 'Удостоверение о повышении квалификации по программе \"Навыки оказания первой помощи\"', 4),
(70, 102, '70.jpg', '0', 3, 'Certificate of Advanced Teacher-Training \"TKT Preparation Course\"', 2),
(71, 102, '71.jpg', '0', 2, 'Cambridge English Certificate in \"Teaching English to Speakers of Other Languages (CELTA)\"', 2),
(72, 102, '72.jpg', '0', 4, 'Cambridge English Teaching Knowledge Test Module 1 \"Language and background to language learning and teaching\"', 2),
(73, 102, '73.jpg', '0', 5, 'Cambridge English Teaching Knowledge Test Module 2 \"Lesson planning and use of resources for language teaching\"', 2),
(74, 102, '74.jpg', '0', 6, 'Cambridge English Teaching Knowledge Test Module 3 \"Managing the teaching and learning process\"', 2),
(78, 129, '78.jpg', '0', 3, 'Diploma of Northern Illinois University \"Master of Science in Education\"', 1),
(79, 129, '79.jpg', '0', 7, 'Удостоверение о повышении квалификации по программе \"Актуальные аспекты преподавания иностранного языка в ВУЗе\"', 4),
(80, 129, '80.jpg', '0', 6, 'Удостоверение о повышении квалификации по программе \"Актуальны проблемы профессионального образования лиц с ОВЗ и инвалидов в условиях инклюзивного образования\"', 4),
(81, 129, '81.jpg', '0', 9, 'Сертификат о повышении квалификации по программе \"Professional development program for teachers of pedagogical specialties within the Universities of the Republic of Kazakshtan\"', 2),
(82, 129, '82.jpg', '0', 8, 'Удостоверение о повышении квалификации по программе \"Основы профессиональной коммуникации и риторики\"', 4),
(83, 129, '83.jpg', '0', 11, 'Удостоверение о повышении квалификации по программе \"Экспертиза и актуализация научно-методического сопровождения образовательного процесса в КАСУ\"', 4),
(84, 129, '84.jpg', '0', 12, 'Удостоверение о повышении квалификации по программе \"Методология и информатизация образовательного процесса\"', 4),
(85, 129, '85.jpg', '0', 10, 'Удостоверение об обучении по программе профессионального развития \"Качество образовательных ресурсов  вуза: мониторинг, измерение, развитие\"', 4),
(86, 129, '86.jpg', '0', 13, 'Сертификат об участии в семинарах на тему \"Формирование лидерских качеств в процессе обучения\"', 2),
(87, 129, '87.jpg', '0', 14, 'Сертификат участия в семинаре повышения квалификации по теме \"Оценка эффективности и пути совершенствования образовательных программ вуза\"', 2),
(88, 129, '88.jpg', '0', 15, 'Newcastle University Certificate \"Enhancing Learning and Teaching in Higher Education\"', 3),
(89, 129, '89.jpg', '0', 16, 'U.S. Embassy Certificate for participation in professional development workshop \"Tips for Teaching Pronunciation\"', 2),
(90, 129, '90.jpg', '0', 18, 'U.S. Embassy Certificate for participation in professional development workshop \"Technology in the ESL Classroom\"', 2),
(91, 129, '91.jpg', '0', 17, 'U.S. Embassy Certificate for participation in professional development workshop \"Rubrics for Assessment\"', 2),
(94, 106, '94.jpg', '0', 3, 'Cambridge English Diploma in Teaching English to Speakers of Other Languages (Delta)', 2),
(95, 106, '95.jpg', '0', 4, 'Сambridge ESOL Certificate in Teaching English to Speakers of Other Languages (CELTA)', 2),
(96, 106, '96.jpg', '0', 5, 'Cambridge ESOL Certificate of Proficiency in English', 2),
(97, 104, '97.jpg', '0', 3, 'Certificate in \"Teaching English as a Foreign Language (TEFL)\", \"Teaching English as a Second or Other Languages (TESOL)\"', 2),
(98, 103, '98.jpg', '0', 3, 'Florida State University Certificate in \"Teaching English as a Foreign Language (TEFL)\"', 2),
(99, 123, '99.jpg', '0', 1, 'Diploma of Federal University of Bahia', 1),
(101, 117, '101.jpg', '0', 2, 'Certificate of Pole Paris Alternance Business School', 2),
(102, 117, '102.jpg', '0', 1, 'Diploma of European Business School', 1),
(103, 127, '103.jpg', '0', 1, 'Diploma of Baylor University College of Arts and Sciences \"Bachelor of Arts\"', 1),
(104, 35, '104.jpg', '0', 1, 'Диплом Новосибирского государственного педагогического университета о присуждении квалификации \"Учитель английского языка\" по специальности \"Иностранный (английский) язык\"', 1),
(105, 129, '105.jpg', '0', 19, 'Certificate of participation in the \"Modeling Leadership in the Classroom\" seminar', 2),
(107, 129, '107.jpg', '0', 21, 'Certificate of participation in \"Academic writing and research\"', 2),
(108, 129, '108.jpg', '0', 20, 'Certificate of participation in the \"Recent Trends in Teaching Methods Instructional and Goals\"', 2),
(109, 129, '109.jpg', '0', 22, 'Сертификат участия в масте-классе \"Групповые методы обучения иностранным языкам\"', 2),
(110, 129, '110.jpg', '0', 23, 'Сертификат участия в мастер-классе \"Интерактивные формы работы в преподавании иностранных языков\"', 2),
(114, 130, '114.jpg', '0', 2, 'Advanced Certificate in Teaching English as a Foreign Language (TEFL)', 2),
(116, 104, '116.jpg', '0', 1, 'Diploma of University of Ulster \"Bachelor of Engineering\"', 1),
(117, 104, '117.jpg', '0', 2, 'Certificate of Achievement in \"Teaching English as a Foreign Language (TEFL)\" and \"Teaching English as a Second or Other Language (TESOL)\"', 2),
(118, 104, '118.jpg', '0', 4, 'Certificate in \"Quigg Golden Construction Law and Practice-related Dissertation Prize\"', 2),
(119, 104, '119.jpg', '0', 5, 'OCR Certificate in \"Using IT Level 2\"', 2),
(120, 104, '120.jpg', '0', 6, 'Благодарственное письмо за участие в Олимпиаде по русскому языку', 3),
(121, 129, '121.jpg', '0', 1, 'Диплом Восточно-Казахстанского государственного университета о присуждении квалификации \"Учитель иностранного языка\" по специальности \"Иностранный язык: два иностранных языка\"', 1),
(122, 129, '122.jpg', '0', 2, 'Диплом магистра Казахстанско-Американского свободного университета о присуждении степени \"Магистр образования (иностранные языки)\" по специальности \"Иностранный язык: два иностранных языка\"', 1),
(123, 102, '123.jpg', '0', 1, 'Диплом Московского государственного открытого педагогического университета о присуждении квалификации \"Учитель английского языка\" по специальности \"Филология\"', 1),
(124, 118, '124.jpg', '0', 1, 'Диплом Гюмрийского государственного педагогического института им. М. Налбандяна о присуждении квалификации \"Учитель английского языка\" по специальности \"Английский язык\"', 1),
(125, 119, '125.jpg', '0', 1, 'Диплом Кузбасской государственной педагогической академии о присвоении квалификации \"Учитель двух иностранных языков (английский и немецкий)\" по специальности \"Иностранный язык\"', 1),
(126, 124, '126.jpg', '0', 1, 'Диплом Восточно-Казахстанского государственного университета о присуждении квалификации \"Учитель английского и казахского языков, переводчик технической литературы\" по специальности \"Иностранные языки\"', 1),
(127, 124, '127.jpg', '0', 2, 'Диплом магистра Восточно-Казахстанского государственного университета о присвоении квалификации \"Магистр педагогики\" по специализации \"Педагогика общеобразовательной школы\"', 1),
(128, 122, '128.jpg', '0', 1, 'Диплом Кузбасской государственной педагогической академии о присуждении квалификации \"Лингвист, переводчик\" по специальности \"Перевод и переводоведение\"', 1),
(129, 122, '129.jpg', '0', 2, 'Диплом о профессиональной переподготовке по программе \"Преподавание английского языка в средней школе\"', 1),
(130, 106, '130.jpg', '0', 1, 'Диплом Московского экономико-финансового института о квалификации \"Менеджер\" по специальности \"Менеджмент организации\"', 1),
(131, 106, '131.jpg', '0', 2, 'Диплом Учебного Центра русского языка МГУ им. М.В. Ломоносова о профессиональной переподготовке по программе \"Методика преподавания русского языка как иностранного\"', 1),
(132, 131, '132.jpg', '0', 1, 'Диплом Новосибирского государственного педагогического университета о присвоении квалификации \"Учитель иностранного языка (английского)\" по специальности \"Иностранный (английский) язык\"', 1),
(133, 131, '133.jpg', '0', 2, 'Диплом о профессиональной переподготовке по программе \"Переводчик в сфере профессиональной коммуникации\"', 1),
(134, 131, '134.jpg', '0', 3, 'Certificate of Completion of the Fulbright Scholarship Program', 2),
(135, 131, '135.jpg', '0', 5, 'St. Giles International London Highgate Course Report (Advanced Level)', 7),
(136, 103, '136.jpg', '0', 2, 'Diploma of Florida State University College of Arts and Science in \"Master of Arts, Slavic\"', 1),
(137, 103, '137.jpg', '0', 1, 'Diploma of Florida State University College of Social Science and Public Policy in \"Master of Arts, Russian and East European Studies\"', 1),
(138, 103, '138.jpg', '0', 4, 'Certificate of the Philological Faculty of the Moscow State University named after M. V. Lomonosov in Advanced Russian', 2),
(139, 131, '139.jpg', '0', 4, 'Test of English as a Foreign Language (TEFL) Internet-based Test (TOEFL iBT)', 2),
(140, 122, '140.jpg', '0', 21, 'Сертификат за выступление по теме \"Влияние личностных качеств учителя на развитие коммуникативных УУД учащихся через использование метода проектов\"', 2),
(141, 122, '141.jpg', '0', 20, 'Сертификат за проведение мастер-класса  по теме \"Организация внеурочной деятельности с учащимися 7-8 классов на примере участия в УСП \"Ее величество наука\"\"', 2),
(142, 122, '142.jpg', '0', 21, 'Сертификат за проведение мастер-класса по теме \"Педагогические возможности блога\"', 2),
(143, 122, '143.jpg', '0', 22, 'Сертификат за участие в семинаре \"Путь к мастерству\"', 2),
(144, 122, '144.jpg', '0', 34, 'Экспертное заключение о рекомендации сетевого проекта \"Australia. Wild and Only\" к использованию в образовательной практике', 6),
(145, 122, '145.jpg', '0', 29, 'Почетная грамота за проведение мастер-класса по теме \"Сетевые проекты в урочной и внеурочной деятельности\"', 3),
(146, 122, '146.jpg', '0', 24, 'Почетная грамота за активную инновационную деятельность по организации и внедрению дистанционного обучения в образовательный процесс', 3),
(147, 132, '147.jpg', '0', 1, 'Diploma of Clayton State University \"Bachelor of Arts\"', 1),
(148, 132, '148.jpg', '0', 2, 'Diploma of Clayton State University \"Bachelor of Science\"', 1),
(149, 132, '149.jpg', '0', 3, 'Diploma of Clayton State University \"Master of Arts\"', 1),
(150, 132, '150.jpg', '0', 4, 'International TEFL and TESOL Training Certificate', 2),
(151, 130, '151.jpg', '0', 1, 'Diploma of Macquarie University \"Master of Chiropractic\"', 1),
(153, 35, '153.jpg', '0', 2, 'Diploma of the Plateau State Polytechnic in \"Business Administration and Management\"', 1),
(155, 122, '155.jpg', '0', 23, 'Выписка об установлении первой квалификационной категории по должности \"Учитель\"', 7),
(156, 122, '156.jpg', '0', 6, 'Удостоверение о повышении квалификации по программе \"Использование педогигики М. Монтессори в самостоятельной деятельности детей раннего возраста и дошкольников\"', 4),
(157, 112, '157.jpg', '0', 1, 'Diploma of Sheffield City Polytechnic \"Bachelor of Education\"', 1),
(158, 112, '158.jpg', '0', 2, 'Document of Department of Education and Science', 5),
(159, 133, '159.jpg', '0', 1, 'Bachelor Degree in the Social Sciences (Economics) University of Leicester', 1),
(160, 133, '160.jpg', '0', 2, 'Postgraduate Diploma in \"Applied Meteorology and Oceanography\" University of Plymouth', 1),
(161, 133, '161.jpg', '0', 3, 'Postgraduate Certificate in Education \"Economics and Business Studies\" University of Bristol', 2),
(163, 133, '163.jpg', '0', 4, 'Certificate in Practice of Management Course Portsmouth Management Centre', 2),
(164, 124, '164.jpg', '0', 10, 'Certificate of Attendance Oxford English Language Teaching Online Conference 2020', 2),
(165, 124, '165.jpg', '0', 5, 'Удостоверение о повышении квалификации по программе \"Английский язык: подготовка к сдаче ЕГЭ в условиях реализации ФГОС СОО\"', 4),
(166, 118, '166.jpg', '0', 2, 'Удостоверение о повышении квалификации по программе \"Английский язык: подготовка к сдаче ЕГЭ в условиях реализации ФГОС СОО\"', 4),
(167, 118, '167.jpg', '0', 12, 'Certificate of Attendance \"The Cambridge English approach to Item writing\"', 2),
(168, 118, '168.jpg', '0', 13, 'Certificate of Attendance \"Preparing your students online for Writing papers in Cambridge English Qualification\"', 2),
(169, 118, '169.jpg', '0', 17, 'Сертификат участия в международной олимпиаде для учителей (преподавателей) английского языка \"Perfect Grammar\"', 2),
(170, 118, '170.jpg', '0', 18, 'Сертификат участия в международной олимпиаде по английскому языку \"Словообразование\"', 2),
(171, 124, '171.jpg', '0', 12, 'Certificate of Attendance \"Engaging activities for online lessons with teens\"', 2),
(172, 124, '172.jpg', '0', 11, 'Certificate of Attendance \"Engaging and motivating students through visible progress\"', 2),
(174, 124, '174.jpg', '0', 3, 'Диплом о профессиональной переподготовке по программе \"Преподавание русского языка как иностранного в образовательной организации\"', 1),
(175, 129, '175.jpg', '0', 24, 'Certificate of Attendance \"The value of task repetition\"', 2),
(176, 122, '176.jpg', '0', 30, 'Certificate of Completion training course \"Playful english\"', 2),
(177, 122, '177.jpg', '0', 28, 'Cambridge University Press Certificate of Attendance \"Speaking to the screen/ overcoming challenges in developing conversation skills in virtual context\"', 2),
(178, 122, '178.jpg', '0', 32, 'Cambridge University Press Certificate of Attendance \"Engaging and motivating students through visible progress\"', 2),
(179, 122, '179.jpg', '0', 33, 'Cambridge University Press Certificate of Attendance \"Motivating teens to take responsibility for their own learning\"', 2),
(181, 122, '181.jpg', '0', 25, 'Cambridge University Press Certificate of Attendance \"Engaging activities for online lessons with teens\"', 2),
(182, 122, '182.jpg', '0', 26, 'Cambridge University Press Certificate of Attendance \"Engaging language learners from home\"', 2),
(183, 122, '183.jpg', '0', 27, 'Cambridge University Press Certificate of Attendance \"The value of task repetition\"', 2),
(184, 134, '184.jpg', '0', 1, 'Дипом бакалавра по направлению подготовки «Педагогическое образование (с двумя профилями подготовки): Английский язык и Немецкий язык»', 1),
(185, 134, '185.jpg', '0', 2, 'Cambridge English Level 2 Certificate in ESOL International (Advanced)', 2),
(186, 134, '186.jpg', '0', 3, 'Cambridge English Teaching Knowledge Test Module 1 \"Language and background to language learning and teaching\"', 2),
(187, 134, '187.jpg', '0', 4, 'Cambridge English Teaching Knowledge Test Module 2 \"Lesson planning and use of resources for language teaching\"', 2),
(188, 134, '188.jpg', '0', 5, 'Cambridge English Teaching Knowledge Test Module 3 \"Managing the teaching and learning process\"', 2),
(189, 124, '189.jpg', '0', 8, 'Сертификат об участии в Марафоне вебинаров по РКИ', 2),
(190, 135, '190.jpg', '0', 3, 'Cambridge English Teaching Knowledge Test Module 1', 2),
(192, 135, '192.jpg', '0', 4, 'Cambridge English Teaching Knowledge Test Module 2', 2),
(194, 124, '194.jpg', '0', 6, 'Сертификат об участии в вебинаре Macmillan Education \"Лексика и Грамматика. Чему и как учить\"', 2),
(195, 122, '195.png', '0', 31, 'Сертификат об участии в мастер-классе \"Интерактивное обучение\"', 2),
(196, 135, '196.jpg', '0', 1, 'Диплом Новосибирского государственного педагогического университета о присвоении квалификации \"Учитель иностранного языка (английского и французского)\"', 1),
(197, 135, '197.jpg', '0', 2, 'Удостоверение о повышении квалификации о дополнительной профессиональной программе \"Инновации в обучении иностранным языкам\"', 4),
(198, 135, '198.jpg', '0', 5, 'The Test of English for International Communication (TOEIC)', 2),
(199, 136, '199.jpg', '0', 1, 'Diploma Bachelor of Arts University of Bristol', 1),
(200, 136, '200.jpg', '0', 2, 'Свидетельство о прохождении стажировки по курсу \"Практический русский язык\" в Кубанском государственном университете', 5),
(201, 124, '201.jpg', '0', 7, 'Сертификат об участии в вебинаре Macmillan Education \"ОГЭ 2021: новый формат — новые материалы\"', 2),
(202, 125, '202.jpg', '0', 3, 'Certificate of Completion the Training Course \"English to Speakers of Other Languages\"', 2),
(203, 125, '203.jpg', '0', 5, 'Certificate of attendance the 1-hour webinar \"Two sides of the same coin: Critical and Creative Thinking in the ELT classroom\"', 2),
(204, 125, '204.jpg', '0', 6, 'Certificate of attendance the 1-hour webinar \"Teacher Activity Groups: an effective model for professional development?\"', 2),
(205, 137, '205.jpg', '0', 1, 'Диплом о присуждении степени бакалавра по направлению \"Лингвистика\"', 1),
(206, 137, '206.jpg', '0', 2, 'Удостоверение о повышении квалификации по дополнительной профессиональной программе \"Инновации в обучении иностранным языкам\"', 4),
(207, 118, '207.jpg', '0', 11, 'Сertificate for attending webinars of Teacher Development Certificate Course, June 2021', 2),
(208, 118, '208.jpg', '0', 6, 'Cambridge Certificate of Attendance TKT Module 1', 2),
(209, 118, '209.jpg', '0', 7, 'Cambridge Certificate of Attendance TKT Module 2', 2),
(210, 118, '210.jpg', '0', 8, 'Cambridge Certificate of Attendance TKT Module 3', 2),
(212, 129, '212.jpg', '0', 25, 'Сертификат об участии в серии лекций, мастер-классов и семинаров школы переводов СПбГУ', 2),
(213, 129, '213.jpg', '0', 26, 'Сертификат об участии в серии лекций и мастер-классов школы переводов СПбГУ', 2),
(214, 129, '214.jpg', '0', 4, 'Удостоверение ТГУ о повышении квалификации по программе \"Модели и технологии интеграции онлайн-курсов в образовательные программы\"', 4),
(215, 138, '215.jpg', '0', 1, 'Bachelor Degree: American Culture and Literature', 1),
(216, 138, '216.jpg', '0', 2, 'Trinity College Certificate in Teaching English to Speakers of Other Languages (TESOL)', 2),
(217, 138, '217.jpg', '0', 3, 'Oxford TEFL Business English Certificate', 2),
(218, 138, '218.jpg', '0', 4, 'Certificate in attending the Oxford TEFL seminar in Teaching Young Learners', 2),
(219, 138, '219.jpg', '0', 5, 'Certificate of attendance the following webinar \"Making sense of how we develop life competencies through ELT\"', 2),
(220, 138, '220.jpg', '0', 6, 'Certificate of attendance the following webinar \"Teaching CLIL (Content and Language Integrated Learning)\"', 2),
(221, 138, '221.jpg', '0', 7, 'Certificate of attendance the following webinar \"Harnessing the power of parents\"', 2),
(222, 138, '222.jpg', '0', 8, 'Certificate of attendance the following webinar \"Upskill your Learners: genuine skills development for Pre A1 Starters, A1 Movers and A2 Flyers\"', 2),
(223, 137, '223.jpg', '0', 3, 'Teacher Development Certificate Course', 2),
(224, 118, '224.jpg', '0', 10, 'Сertificate for attending webinars of Teacher Development Certificate Course, January 2022', 2),
(225, 122, '225.jpg', '0', 18, 'Teacher Development Certificate Course, June 2021', 2),
(226, 122, '226.jpg', '0', 19, 'Teacher Development Certificate Course, January 2022', 2),
(229, 129, '229.jpg', '0', 5, 'Удостоверение о повышении квалификации по программе \"Современные подходы к обучению устному и письменному переводу\"\"', 4),
(230, 122, '230.jpg', '0', 13, 'Oxford Certificate of Attendance — English Language Teaching Online Conference Block 1', 2),
(231, 122, '231.jpg', '0', 14, 'Oxford Certificate of Attendance — English Language Teaching Online Conference Block 3', 2),
(232, 122, '232.jpg', '0', 16, 'Oxford Certificate of Attendance — English Language Teaching Online Conference Block 4', 2),
(233, 122, '233.jpg', '0', 3, 'Удостоверение о повышении квалификации по программе \"Английский язык. Подготовка к сдаче ЕГЭ\"', 4),
(234, 122, '234.jpg', '0', 4, 'Удостоверение о повышении квалификации по программе \"Развитие профессиональных навыков при подготовке к сдаче ОГЭ по английскому языку\"', 4),
(235, 122, '235.jpg', '0', 20, 'Teacher Development Certificate, May 2022', 2),
(236, 119, '236.png', '0', 5, 'Certificate of completion the course \"Making online lessons engaging\"', 2),
(237, 139, '237.jpg', '0', 1, 'Диплом Новосибирского государственного педагогического университета с отличием по направлению подготовки «Лингвистика»', 1),
(238, 139, '238.jpg', '0', 2, 'Диплом о профессиональной переподготовке по программе «Педагогическое образование: Английский язык в образовательных организациях»', 1),
(241, 139, '241.jpg', '0', 3, 'TEFL (Teaching English as a Foreign Language) Certificate', 2),
(242, 139, '242.jpg', '0', 5, 'TEFL (Teaching English as a Foreign Language) Certificate in English Grammar', 2),
(243, 139, '243.jpg', '0', 6, 'Certificate of attendance \"Teaching teens: motivating unmotivated\"', 2),
(244, 139, '244.jpg', '0', 7, 'Certificate of attendance «Teaching for B2 First for the first time! Developing productive skills»', 2),
(245, 139, '245.jpg', '0', 8, 'Certificate of attendance \"Classroom management success in 7 days or less\"', 2),
(246, 139, '246.jpg', '0', 9, 'Сертификат участника курса лекций по теме \"Практический тренинг: эссе на основе таблиц и диаграмм ЕГЭ-2022\"', 2),
(247, 139, '247.jpg', '0', 11, 'Сертификат участника курса лекций по теме \"Тренинг по экспертному оцениванию: эссе на основе таблиц и диаграмм ЕГЭ-2022\"', 2),
(248, 139, '248.jpg', '0', 10, 'Сертификат участника курса лекций по теме \"Практический тренинг: Устная часть ЕГЭ-2022\"', 2),
(249, 139, '249.jpg', '0', 12, 'Сертификат участника курса лекций по теме \"Тренинг по экспертному оцениванию: устная часть ЕГЭ-2022\"', 2),
(250, 139, '250.jpg', '0', 13, 'Certificate of attendance \"Teaching Lexis for OGE/EGE\"', 2),
(251, 139, '251.jpg', '0', 14, 'Сертификат о прохождении курса \"Подготовка учащихся к итоговой аттестации по английскому языку в 9-х и 11-х классах\"', 2),
(252, 139, '252.jpg', '0', 15, 'Серификат об участии в вебинаре на тему \"Онлайн английский для младших классов\"', 2),
(253, 139, '253.jpg', '0', 16, 'Certificate of participation in the National Geographic learning webinar \"Nurturing reading success in young learners of English\"', 2),
(254, 139, '254.jpg', '0', 17, 'Certificate of participation in a series of webinars \"Brush up your skills\"', 2),
(255, 139, '255.jpg', '0', 18, 'Сертификат об участии в курсе Trendy English Academy \"Старые игры по-новому\"', 2),
(256, 139, '256.jpg', '0', 19, 'Сертификат об участии в курсе Trendy English Academy \"Командообразование\"', 2),
(257, 139, '257.jpg', '0', 20, 'Сертификат об участии в курсе Trendy English Academy \"Как превращать упражнения в игры\"', 2),
(258, 139, '258.jpg', '0', 21, 'Сертификат об участии в курсе Trendy English Academy \"Игры для каждого этапа урока\"', 2),
(259, 139, '259.jpg', '0', 22, 'Certificate of attendance \"Cool warming up activities\"', 2),
(260, 139, '260.jpg', '0', 23, 'Certificate of attendance \"Best back to school activities\"', 2),
(261, 140, '261.jpg', '0', 3, 'TESOL (Teaching English for Speakers of Other Languages) Certificate', 2),
(262, 140, '262.jpg', '0', 4, 'TEFL (Teaching English as a Foreign Language) Certificate', 2),
(263, 140, '263.jpg', '0', 5, 'Certificate of participation for attending the four-week online course \"Life Skills in the English Language Classroom\"', 2),
(264, 140, '264.jpg', '0', 1, 'Diploma Bachelor of English Language and Literature', 1),
(265, 140, '265.jpg', '0', 2, 'Diploma Master of Teaching English as a Foreign Language and Applied Linguistics', 1),
(266, 140, '266.jpg', '0', 6, 'Сertificate of Participation in the Conference \"Rethinking EFL Learners Assessment in LMD Context/ Between Individual Renewal and Collective Construction\"', 2),
(267, 118, '267.jpg', '0', 9, 'Сertificate for attending webinars of Teacher Development Certificate Course, December 2022', 2),
(268, 122, '268.jpg', '0', 17, 'Certificate for attending Teacher Development Certificate Course, December 2022', 2),
(269, 122, '269.jpg', '0', 15, 'Certificate for Atennding in English Language Teaching Online Conference, Chapter 1 Block 1', 2),
(270, 122, '270.jpg', '0', 12, 'Certificate for Atennding in English Language Teaching Online Conference, Chapter 3 Block 2', 2),
(271, 122, '271.jpg', '0', 11, 'Certificate for Atennding in English Language Teaching Online Conference, Chapter 3 Block 4', 2),
(273, 141, '273.jpg', '0', 3, 'Cambridge Diploma in English Language Teaching to Adults (DELTA), Module Two', 1),
(274, 141, '274.jpg', '0', 5, 'Cambridge Certificate of English Language Teaching to Adults (CELTA)', 2),
(275, 141, '275.jpg', '0', 6, 'Cambridge Teaching Knowledge Test (TKT), Module 1', 2),
(276, 141, '276.jpg', '0', 7, 'Cambridge Teaching Knowledge Test (TKT), Module 2', 2),
(277, 141, '277.jpg', '0', 8, 'Cambridge Teaching Knowledge Test (TKT), Module 3', 2),
(278, 141, '278.jpg', '0', 9, 'Cambridge Teaching Knowledge Test (TKT), Young Learners', 2),
(279, 141, '279.jpg', '0', 10, 'Cambridge Certificate of completion \"Cambridge Assessment Emglish Train the Trainer course\"', 2),
(280, 141, '280.jpg', '0', 11, 'Certificate of participation \"IELTS Preparation — Academic Module\"', 2),
(281, 141, '281.jpg', '0', 12, 'Certificate of comletion the Course \"IELTS — Coaching\"', 2),
(283, 141, '283.jpg', '0', 14, 'Certificate of completion course in \"Communicative English\"', 2),
(284, 141, '284.jpg', '0', 2, 'Cambridge Diploma in English Language Teaching to Adults (DELTA), Module One', 1),
(285, 141, '285.jpg', '0', 13, 'Certificate of Teachers English Academy \"Course in English\"', 2),
(286, 122, '286.jpg', '0', 9, 'Teacher Development Certificate, April 2023', 2),
(287, 122, '287.jpg', '0', 10, 'Certificate of Attendance for \"Supporting Students through Social-Emotional Learning\"', 2),
(288, 141, '288.jpg', '0', 1, 'Cambridge English Level 7 Diploma in Teaching English to Speakers of Other Languages (DELTA)', 1),
(289, 141, '289.jpg', '0', 4, 'Cambridge Diploma in English Language Teaching to Adults (DELTA), Module Three', 1),
(290, 139, '290.jpg', '0', 4, 'Удостоверение о повышении квалификации по дополнительной профессиональной программе \"Психология развития и возрастная психология\"', 4);
